# Generated by Django 5.0.7 on 2024-09-06 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('site_link', models.URLField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('title', models.CharField(max_length=200, null=True)),
                ('summary', models.TextField(blank=True, max_length=5000, null=True)),
                ('posted_as', models.CharField(choices=[('Blogs', 'Blogs'), ('App', 'App')], max_length=10)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_school', models.BooleanField(default=False)),
                ('is_auto', models.BooleanField(default=False)),
                ('is_shopping', models.BooleanField(default=False)),
                ('is_social', models.BooleanField(default=False)),
                ('is_blockchain', models.BooleanField(default=False)),
                ('is_fashion', models.BooleanField(default=False)),
                ('is_real_estate', models.BooleanField(default=False)),
                ('is_hotel', models.BooleanField(default=False)),
                ('is_others', models.BooleanField(default=False)),
                ('is_appdev', models.BooleanField(default=False)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_cross', models.BooleanField(default=False)),
                ('is_web', models.BooleanField(default=False)),
                ('is_markerting', models.BooleanField(default=False)),
                ('is_SEO', models.BooleanField(default=False)),
                ('is_SMM', models.BooleanField(default=False)),
                ('is_Emailing', models.BooleanField(default=False)),
                ('is_PPC', models.BooleanField(default=False)),
                ('is_content', models.BooleanField(default=False)),
                ('is_productcat', models.BooleanField(default=False)),
                ('is_ERP', models.BooleanField(default=False)),
                ('is_CRM', models.BooleanField(default=False)),
                ('is_CMS', models.BooleanField(default=False)),
                ('is_CloudB', models.BooleanField(default=False)),
                ('is_BI', models.BooleanField(default=False)),
                ('is_cyber_security', models.BooleanField(default=False)),
                ('is_tips', models.BooleanField(default=False)),
                ('is_guide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_for', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('communication_method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('google_meet', 'Google Meet'), ('easy_jay_site', 'Easy Jay Site'), ('zoom', 'Zoom'), ('skype', 'Skype'), ('phone_call', 'Phone Call'), ('email', 'Email'), ('on_site', 'On Site')], default='', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-booked_for'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('user', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogapp.blogs')),
            ],
        ),
        migrations.CreateModel(
            name='CookiesConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_given', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
